### PR TITLE
fixed deprecated use of np.bool

### PR DESCRIPTION
**Pull request by hyruuk**
Solves #35

### CODE REVIEW

**Comment by lucia-lux** [comment]
Hey! I'm still getting the error about np.bool being deprecated despite using the latest version from pypi (0.2.6).

**Comment by hyruuk** [comment]
Yes, the easiest way to proceed for now would be to clone the repo on your local machine and then install it by running 
```
pip install -e .
```  
while in the folder.

**Comment by lucia-lux** [comment]
Great, thanks!

**Comment by ranggakd** [comment]
is there a problem with updating this repo into the Pypi package that we should know about? It seems easier to install the updated version there rather than directly clone this repo to solve this `bool` problem. People seem to comeback to this problem apparently #39.

**Pull request merged**
