### PR TITLE
Parameterize showfliers and apply alpha to stripplot

### PR DESCRIPTION
**Pull request by benjaminsaljooghi**

### CODE REVIEW

**Comment by pog87** [comment]
Hi @benjaminsaljooghi and thanks for the PR. 
Sorry for the late answer, I had lots of tasks to end at my work.

both requests:
1. Add alpha to stripplot
2. Parameterize showfliers

are technically legit and the code you propose does not seem to introduce conficts of any kind.

However I personally find that both options go in another direction than the RainCloud philosophy. Namely:

1. Adding alpha to stripplot introduces the same `alpha` as the KDE cloud, without great benefits, since the `jitter` avoids overlaps. One could think about adding a `stripplot_alpha` parameter, which could make the whole function more difficult to use than is already

2. Parameterizing showfliers allows the user to hide the outliers, hiding such informations form the view. Of course the stripplot shows such points, but it becomes harder to distinguish points over the [1,4]-quartile interval from extreme outliers.

Of course this is my opinion, and I can be wrong.
Could you please specify the reason you introduced these two options and what is the benefit for the plot viewer?

**Comment by benjaminsaljooghi** [comment]
Hi @pog87 thanks for the response.

1. I find that the jitter in some cases is not sufficient. Increasing the jitter increases the width of the plot which is sometimes non-ideal. I find that the alpha can be a more concise way of getting a visualization of the density of observations. I don't think adding additional parameters makes the function more difficult to use so long as we use default values.

2. With the data I have at the moment, I have an extreme quantity of outliers which pollutes the visualization.

I can provide example graphs to demonstrate my point if you like.

**Comment by pog87** [comment]
One image is sufficient, thanks

**Comment by pog87** [comment]
Hi @benjaminsaljooghi thanks for your reply.

I begin to see your point, could you please provide one or two example graph?

Best,
Davide

**Comment by benjaminsaljooghi** [comment]
Hi @pog87 

Sorry about the delay.

raincloud_example

Here is an example where I have show_fliers = True and where I have alpha = False.

My view is that:

- The alpha is useful here for getting a quick visual indication of density, but where increasing the jitter would undesirably increase the width of the total block.
- The fliers are superfluous here given the pointplot.

Thank you for your consideration!

**Comment by pog87** [comment]
Hi @benjaminsaljooghi 

>Sorry about the delay.

well...I'm not paying you, so never be sorry about time :-)

You definitely have a point. Even if your example is improbable with real-life data a generic user might want to have these options.
 
I shall now merge your PR. But I'll change `True` as default for showfliers; I have also decided to separate `alpha_cloud` and `alpha_rain` or something similar.

I want to warmly thank you for your contribution!

**Comment by pog87** [comment]
From version `.0.2.0` this feature is now changed to `box_showfliers`, `rain_alpha`, etc ...

**Pull request merged**
