### PR TITLE
run tests on notebooks in CI

### PR DESCRIPTION
**Pull request by sappelhoff**
In this PR I add GitHub actions, so that the example notebooks are executed on GitHub's servers on each commit ... and if they don't pass, we get an error message.

This should be good to verify that new pull requests etc. work as expected.

This PR might need to be merged first, for the changes to take effect.

### CODE REVIEW

**Comment by pog87** [comment]
just to be clear, do you mean that if the notebooks get a single cell error, a PR won't pass?

**Comment by sappelhoff** [comment]
yes, that's how it would work

**Comment by sappelhoff** [comment]
it can still be merged, of course ... but it would show that something is off

**Comment by pog87** [comment]
sounds good

**Pull request merged**
